/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author georgiosloulakis
 */
public class EvaluationForm extends javax.swing.JFrame {

    /**
     * Creates new form EvaluationForm
     */
    public EvaluationForm() {
        initComponents();
          //setSize(600,750);
        
          setResizable(false);
          
    }
      public void Create() throws IOException
      {
        File file = new File("Data.txt");
        if (file.createNewFile()) {
            System.out.println("File"+ file.getName()+"was created.");
        }else System.out.println("File"+ file.getName()+"could not be created.");
    }
      
      public void infoEvaluation(){
          String result0 = Result0.getText();
          String Result1 = result1.getText();
          String result2 = Result2.getText();
          String result3 = Result3.getText();
          String result4 = Result4.getText();
          String result5 = Result5.getText();
          String result6 = Result6.getText();
          String result7 = Result7.getText();
          String result8 = Result8.getText();
          String result9 = Result9.getText();
          String result10 = Result10.getText();
          String result11 = Result11.getText();
          String result12 = Result12.getText();
          String result13 = Result13.getText();
          String result14 = Result14.getText();
          String result15 = Result15.getText();
          String result16 = Result16.getText();
          String result17 = Result17.getText();
          try{
              File file = new File("Data.txt");
              FileWriter writer = new FileWriter(file,true);
                  writer.write(result0);
                  writer.write(",");
                  writer.write(Result1);
                  writer.write(",");
                  writer.write(result2);
                  writer.write(",");
                  writer.write(result3);
                  writer.write(",");
                  writer.write(result4);
                  writer.write(",");
                  writer.write(result5);
                  writer.write(",");
                  writer.write(result6);
                  writer.write(",");
                  writer.write(result7);
                  writer.write(",");
                  writer.write(result8);
                  writer.write(",");
                  writer.write(result9);
                  writer.write(",");
                  writer.write(result10);
                  writer.write(",");
                  writer.write(result11);
                  writer.write(",");
                  writer.write(result12);
                  writer.write(",");
                  writer.write(result13);
                  writer.write(",");
                  writer.write(result14);
                  writer.write(",");
                  writer.write(result15);
                  writer.write(",");
                  writer.write(result16);
                  writer.write(",");
                  writer.write(result17);
                  writer.write("\n");
                  writer.close();
              
               
          }catch(IOException e){
              
          }
          
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        five = new javax.swing.JRadioButton();
        ten = new javax.swing.JRadioButton();
        fifteen = new javax.swing.JRadioButton();
        fifteen1 = new javax.swing.JRadioButton();
        five1 = new javax.swing.JRadioButton();
        ten1 = new javax.swing.JRadioButton();
        fifteen2 = new javax.swing.JRadioButton();
        five2 = new javax.swing.JRadioButton();
        ten2 = new javax.swing.JRadioButton();
        fifteen3 = new javax.swing.JRadioButton();
        five3 = new javax.swing.JRadioButton();
        ten3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        ten16 = new javax.swing.JRadioButton();
        ten17 = new javax.swing.JRadioButton();
        fifteen17 = new javax.swing.JRadioButton();
        five17 = new javax.swing.JRadioButton();
        fifteen16 = new javax.swing.JRadioButton();
        five16 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        ten14 = new javax.swing.JRadioButton();
        five11 = new javax.swing.JRadioButton();
        ten11 = new javax.swing.JRadioButton();
        ten15 = new javax.swing.JRadioButton();
        fifteen15 = new javax.swing.JRadioButton();
        five15 = new javax.swing.JRadioButton();
        fifteen11 = new javax.swing.JRadioButton();
        fifteen12 = new javax.swing.JRadioButton();
        five12 = new javax.swing.JRadioButton();
        ten12 = new javax.swing.JRadioButton();
        fifteen13 = new javax.swing.JRadioButton();
        five13 = new javax.swing.JRadioButton();
        ten13 = new javax.swing.JRadioButton();
        fifteen14 = new javax.swing.JRadioButton();
        five14 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fifteen8 = new javax.swing.JRadioButton();
        five8 = new javax.swing.JRadioButton();
        ten8 = new javax.swing.JRadioButton();
        fifteen9 = new javax.swing.JRadioButton();
        five9 = new javax.swing.JRadioButton();
        ten9 = new javax.swing.JRadioButton();
        fifteen10 = new javax.swing.JRadioButton();
        five10 = new javax.swing.JRadioButton();
        ten10 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        five7 = new javax.swing.JRadioButton();
        ten7 = new javax.swing.JRadioButton();
        five4 = new javax.swing.JRadioButton();
        ten4 = new javax.swing.JRadioButton();
        fifteen4 = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        fifteen5 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        five5 = new javax.swing.JRadioButton();
        ten5 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        fifteen6 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        five6 = new javax.swing.JRadioButton();
        ten6 = new javax.swing.JRadioButton();
        fifteen7 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Result0 = new javax.swing.JLabel();
        result1 = new javax.swing.JLabel();
        Result2 = new javax.swing.JLabel();
        Result3 = new javax.swing.JLabel();
        Result4 = new javax.swing.JLabel();
        Result5 = new javax.swing.JLabel();
        Result6 = new javax.swing.JLabel();
        Result7 = new javax.swing.JLabel();
        Result8 = new javax.swing.JLabel();
        Result9 = new javax.swing.JLabel();
        Result10 = new javax.swing.JLabel();
        Result11 = new javax.swing.JLabel();
        Result12 = new javax.swing.JLabel();
        Result13 = new javax.swing.JLabel();
        Result14 = new javax.swing.JLabel();
        Result15 = new javax.swing.JLabel();
        Result16 = new javax.swing.JLabel();
        Result17 = new javax.swing.JLabel();

        jTextField3.setText("jTextField1");

        jLabel27.setText("jLabel19");

        jLabel28.setText("jLabel19");

        jLabel29.setText("jLabel19");

        jLabel30.setText("jLabel19");

        jLabel44.setText("jLabel19");

        jLabel45.setText("jLabel19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel37.setForeground(new java.awt.Color(118, 11, 11));
        jLabel37.setText("Greeting");

        jLabel1.setText("Took responsibility for the caller's issues and");

        jLabel2.setText("Correctly greeted the caller and introduced themselves");

        jLabel3.setText("Accurately identified the caller and the account");

        jLabel4.setText("Effectively transfer the call to the proper department/agent if necessary");

        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        ten.setText("10");
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });

        fifteen.setText("15");
        fifteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteenActionPerformed(evt);
            }
        });

        fifteen1.setText("15");
        fifteen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen1ActionPerformed(evt);
            }
        });

        five1.setText("5");
        five1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five1ActionPerformed(evt);
            }
        });

        ten1.setText("10");
        ten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten1ActionPerformed(evt);
            }
        });

        fifteen2.setText("15");
        fifteen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen2ActionPerformed(evt);
            }
        });

        five2.setText("5");
        five2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five2ActionPerformed(evt);
            }
        });

        ten2.setText("10");
        ten2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten2ActionPerformed(evt);
            }
        });

        fifteen3.setText("15");
        fifteen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen3ActionPerformed(evt);
            }
        });

        five3.setText("5");
        five3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five3ActionPerformed(evt);
            }
        });

        ten3.setText("10");
        ten3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(five)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fifteen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(five1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ten1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fifteen1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(five3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ten3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fifteen3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(five2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ten2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fifteen2)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five)
                            .addComponent(ten)
                            .addComponent(fifteen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five1)
                            .addComponent(ten1)
                            .addComponent(fifteen1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(five2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ten2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fifteen2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five3)
                            .addComponent(ten3)
                            .addComponent(fifteen3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setText("Offered to assist with anything else they might need");

        jLabel18.setText("Thanked the customer for calling ");

        jLabel41.setForeground(new java.awt.Color(118, 11, 11));
        jLabel41.setText("Wrapping-up");

        ten16.setText("10");
        ten16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten16ActionPerformed(evt);
            }
        });

        ten17.setText("10");
        ten17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten17ActionPerformed(evt);
            }
        });

        fifteen17.setText("15");
        fifteen17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen17ActionPerformed(evt);
            }
        });

        five17.setText("5");
        five17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five17ActionPerformed(evt);
            }
        });

        fifteen16.setText("15");
        fifteen16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen16ActionPerformed(evt);
            }
        });

        five16.setText("5");
        five16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(five17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen17))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(five16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen16)))
                        .addGap(14, 14, 14))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five16)
                            .addComponent(ten16)
                            .addComponent(fifteen16))
                        .addGap(28, 28, 28))
                    .addComponent(five17)
                    .addComponent(ten17)
                    .addComponent(fifteen17))
                .addContainerGap())
        );

        ten14.setText("10");
        ten14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten14ActionPerformed(evt);
            }
        });

        five11.setText("5");
        five11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five11ActionPerformed(evt);
            }
        });

        ten11.setText("10");
        ten11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten11ActionPerformed(evt);
            }
        });

        ten15.setText("10");
        ten15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten15ActionPerformed(evt);
            }
        });

        fifteen15.setText("15");
        fifteen15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen15ActionPerformed(evt);
            }
        });

        five15.setText("5");
        five15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five15ActionPerformed(evt);
            }
        });

        fifteen11.setText("15");
        fifteen11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen11ActionPerformed(evt);
            }
        });

        fifteen12.setText("15");
        fifteen12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen12ActionPerformed(evt);
            }
        });

        five12.setText("5");
        five12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five12ActionPerformed(evt);
            }
        });

        ten12.setText("10");
        ten12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten12ActionPerformed(evt);
            }
        });

        fifteen13.setText("15");
        fifteen13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen13ActionPerformed(evt);
            }
        });

        five13.setText("5");
        five13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five13ActionPerformed(evt);
            }
        });

        ten13.setText("10");
        ten13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten13ActionPerformed(evt);
            }
        });

        fifteen14.setText("15");
        fifteen14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen14ActionPerformed(evt);
            }
        });

        five14.setText("5");
        five14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five14ActionPerformed(evt);
            }
        });

        jLabel16.setText("Spoke out of line/ was rude to the customer (deduct points)");

        jLabel40.setForeground(new java.awt.Color(118, 11, 11));
        jLabel40.setText("Call Etiquette");

        jLabel12.setText("The agent was attentive to the caller's comments/concerns ");

        jLabel13.setText("The agent never interrupted the caller");

        jLabel14.setText("There were no long pauses in the conversation");

        jLabel15.setText("The agent spoke highly of all department especially ones where the problem occurred ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(five11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ten11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fifteen11))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(five12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ten12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fifteen12))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(five14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ten14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fifteen14))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(five13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ten13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fifteen13)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(five15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen15)))
                        .addGap(14, 14, 14))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five11)
                            .addComponent(ten11)
                            .addComponent(fifteen11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five12)
                            .addComponent(ten12)
                            .addComponent(fifteen12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(five13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ten13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fifteen13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five14)
                            .addComponent(ten14)
                            .addComponent(fifteen14))
                        .addGap(28, 28, 28))
                    .addComponent(five15)
                    .addComponent(ten15)
                    .addComponent(fifteen15)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fifteen8.setText("15");
        fifteen8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen8ActionPerformed(evt);
            }
        });

        five8.setText("5");
        five8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five8ActionPerformed(evt);
            }
        });

        ten8.setText("10");
        ten8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten8ActionPerformed(evt);
            }
        });

        fifteen9.setText("15");
        fifteen9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen9ActionPerformed(evt);
            }
        });

        five9.setText("5");
        five9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five9ActionPerformed(evt);
            }
        });

        ten9.setText("10");
        ten9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten9ActionPerformed(evt);
            }
        });

        fifteen10.setText("15");
        fifteen10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen10ActionPerformed(evt);
            }
        });

        five10.setText("5");
        five10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five10ActionPerformed(evt);
            }
        });

        ten10.setText("10");
        ten10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten10ActionPerformed(evt);
            }
        });

        jLabel10.setText("Set realistic time-frames for the problem to be taken care of ");

        jLabel11.setText("Explained and determine the appropriate solution");

        jLabel9.setText("Resolved the issue swiftly and immediate if possible ");

        jLabel39.setForeground(new java.awt.Color(118, 11, 11));
        jLabel39.setText("Resolution");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(five8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(five10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(five9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen9)))
                        .addGap(19, 19, 19))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five8)
                            .addComponent(ten8)
                            .addComponent(fifteen8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(five9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ten9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fifteen9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five10)
                            .addComponent(ten10)
                            .addComponent(fifteen10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)))
                .addContainerGap())
        );

        five7.setText("5");
        five7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five7ActionPerformed(evt);
            }
        });

        ten7.setText("10");
        ten7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten7ActionPerformed(evt);
            }
        });

        five4.setText("5");
        five4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five4ActionPerformed(evt);
            }
        });

        ten4.setText("10");
        ten4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten4ActionPerformed(evt);
            }
        });

        fifteen4.setText("15");
        fifteen4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen4ActionPerformed(evt);
            }
        });

        jLabel38.setForeground(new java.awt.Color(118, 11, 11));
        jLabel38.setText("Problem Solving");

        fifteen5.setText("15");
        fifteen5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Assured them you were there to help");

        jLabel6.setText("Sought out clues, and asked only relevant questions");

        five5.setText("5");
        five5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five5ActionPerformed(evt);
            }
        });

        ten5.setText("10");
        ten5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Created an accurate action plan to solve the problem");

        fifteen6.setText("15");
        fifteen6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Limited the hold time ");

        five6.setText("5");
        five6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five6ActionPerformed(evt);
            }
        });

        ten6.setText("10");
        ten6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten6ActionPerformed(evt);
            }
        });

        fifteen7.setText("15");
        fifteen7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteen7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(five4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(five5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen5))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(five7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen7))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(five6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifteen6)))
                        .addGap(20, 20, 20))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five4)
                            .addComponent(ten4)
                            .addComponent(fifteen4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five5)
                            .addComponent(ten5)
                            .addComponent(fifteen5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(five6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ten6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fifteen6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(five7)
                            .addComponent(ten7)
                            .addComponent(fifteen7)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );

        jButton1.setText("Results");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Result0.setForeground(new java.awt.Color(238, 238, 238));

        result1.setForeground(new java.awt.Color(238, 238, 238));

        Result2.setForeground(new java.awt.Color(238, 238, 238));

        Result3.setForeground(new java.awt.Color(238, 238, 238));

        Result4.setForeground(new java.awt.Color(238, 238, 238));

        Result5.setForeground(new java.awt.Color(238, 238, 238));

        Result6.setForeground(new java.awt.Color(238, 238, 238));

        Result7.setForeground(new java.awt.Color(238, 238, 238));

        Result8.setForeground(new java.awt.Color(238, 238, 238));

        Result9.setForeground(new java.awt.Color(238, 238, 238));

        Result10.setForeground(new java.awt.Color(238, 238, 238));

        Result11.setForeground(new java.awt.Color(238, 238, 238));

        Result12.setForeground(new java.awt.Color(238, 238, 238));

        Result13.setForeground(new java.awt.Color(238, 238, 238));

        Result14.setForeground(new java.awt.Color(238, 238, 238));

        Result15.setForeground(new java.awt.Color(238, 238, 238));

        Result16.setForeground(new java.awt.Color(238, 238, 238));

        Result17.setForeground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(16, 16, 16)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Result0)
                                    .addComponent(result1)
                                    .addComponent(Result2)
                                    .addComponent(Result3)
                                    .addComponent(Result4)
                                    .addComponent(Result5)
                                    .addComponent(Result6)
                                    .addComponent(Result8)
                                    .addComponent(Result9)
                                    .addComponent(Result10)
                                    .addComponent(Result11)
                                    .addComponent(Result12)
                                    .addComponent(Result13)
                                    .addComponent(Result7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(Result14, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(Result15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(Result16, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(Result17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Result0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(result1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Result4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result7)
                        .addGap(26, 26, 26))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Result8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result10)
                        .addGap(78, 78, 78)
                        .addComponent(Result11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Result16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result17))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        if (five.isSelected()) {
            ten.setSelected(false);
            fifteen.setSelected(false);
            Result0.setText(five.getText());
            
        }
    }//GEN-LAST:event_fiveActionPerformed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        // TODO add your handling code here:
            if (ten.isSelected()) {
            five.setSelected(false);
            fifteen.setSelected(false);}
            Result0.setText(ten.getText());
          
    }//GEN-LAST:event_tenActionPerformed

    private void fifteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteenActionPerformed
        // TODO add your handling code here:
           if (fifteen.isSelected()) {
            five.setSelected(false);
            ten.setSelected(false);}
           Result0.setText(fifteen.getText());
           
    }//GEN-LAST:event_fifteenActionPerformed

    private void fifteen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen1ActionPerformed
        // TODO add your handling code here:
         if (fifteen1.isSelected()) {
            five1.setSelected(false);
            ten1.setSelected(false);}
            result1.setText(fifteen1.getText());
           
    }//GEN-LAST:event_fifteen1ActionPerformed

    private void five1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five1ActionPerformed
        // TODO add your handling code here:
        if (five1.isSelected()) {
            ten1.setSelected(false);
            fifteen1.setSelected(false);
            result1.setText(five1.getText());
           
        }
    }//GEN-LAST:event_five1ActionPerformed

    private void ten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten1ActionPerformed
        // TODO add your handling code here:
        if (ten1.isSelected()) {
            five1.setSelected(false);
            fifteen1.setSelected(false);}
            result1.setText(ten1.getText());
            
    }//GEN-LAST:event_ten1ActionPerformed

    private void fifteen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen2ActionPerformed
        // TODO add your handling code here:
         if (fifteen2.isSelected()) {
            five2.setSelected(false);
            ten2.setSelected(false);}
            Result2.setText(fifteen2.getText());
           
    }//GEN-LAST:event_fifteen2ActionPerformed

    private void five2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five2ActionPerformed
        // TODO add your handling code here:
        if (five2.isSelected()) {
            ten2.setSelected(false);
            fifteen2.setSelected(false);
            Result2.setText(five2.getText());
           
        }
    }//GEN-LAST:event_five2ActionPerformed

    private void ten2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten2ActionPerformed
        // TODO add your handling code here:
        if (ten2.isSelected()) {
            five2.setSelected(false);
            fifteen2.setSelected(false);}
            Result2.setText(ten2.getText());
           
    }//GEN-LAST:event_ten2ActionPerformed

    private void fifteen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen3ActionPerformed
        // TODO add your handling code here:
         if (fifteen3.isSelected()) {
            five3.setSelected(false);
            ten3.setSelected(false);}
            Result3.setText(fifteen3.getText());
            
    }//GEN-LAST:event_fifteen3ActionPerformed

    private void five3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five3ActionPerformed
        // TODO add your handling code here:
        if (five3.isSelected()) {
            ten3.setSelected(false);
            fifteen3.setSelected(false);
            Result3.setText(five3.getText());
            
        }
    }//GEN-LAST:event_five3ActionPerformed

    private void ten3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten3ActionPerformed
        // TODO add your handling code here:
        if (ten3.isSelected()) {
            five3.setSelected(false);
            fifteen3.setSelected(false);}
            Result3.setText(ten3.getText());
           
    }//GEN-LAST:event_ten3ActionPerformed

    private void fifteen4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen4ActionPerformed
        // TODO add your handling code here:
         if (fifteen4.isSelected()) {
            five4.setSelected(false);
            ten4.setSelected(false);}
            Result4.setText(fifteen4.getText());
           
    }//GEN-LAST:event_fifteen4ActionPerformed

    private void fifteen5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen5ActionPerformed
        // TODO add your handling code here:
         if (fifteen5.isSelected()) {
            five5.setSelected(false);
            ten5.setSelected(false);}
            Result5.setText(fifteen5.getText());
            
    }//GEN-LAST:event_fifteen5ActionPerformed

    private void five5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five5ActionPerformed
        // TODO add your handling code here:
        if (five5.isSelected()) {
            ten5.setSelected(false);
            fifteen5.setSelected(false);
            Result5.setText(five5.getText());
            
        }
    }//GEN-LAST:event_five5ActionPerformed

    private void ten5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten5ActionPerformed
        // TODO add your handling code here:
        if (ten10.isSelected()) {
            five10.setSelected(false);
            fifteen10.setSelected(false);}
            Result5.setText(ten10.getText());
            
    }//GEN-LAST:event_ten5ActionPerformed

    private void fifteen6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen6ActionPerformed
        // TODO add your handling code here:
         if (fifteen6.isSelected()) {
            five6.setSelected(false);
            ten6.setSelected(false);}
            Result6.setText(fifteen6.getText());
            
    }//GEN-LAST:event_fifteen6ActionPerformed

    private void five6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five6ActionPerformed
        // TODO add your handling code here:
        if (five6.isSelected()) {
            ten6.setSelected(false);
            fifteen6.setSelected(false);
            Result6.setText(five6.getText());
           
        }
    }//GEN-LAST:event_five6ActionPerformed

    private void ten6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten6ActionPerformed
        // TODO add your handling code here:
        if (ten6.isSelected()) {
            five6.setSelected(false);
            fifteen6.setSelected(false);}
            Result6.setText(ten6.getText());
           
    }//GEN-LAST:event_ten6ActionPerformed

    private void fifteen7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen7ActionPerformed
        // TODO add your handling code here:
         if (fifteen7.isSelected()) {
            five7.setSelected(false);
            ten7.setSelected(false);}
            Result7.setText(fifteen7.getText());
            
    }//GEN-LAST:event_fifteen7ActionPerformed

    private void five7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five7ActionPerformed
        // TODO add your handling code here:
        if (five7.isSelected()) {
            ten7.setSelected(false);
            fifteen7.setSelected(false);
        }
        Result7.setText(five7.getText());
       
    }//GEN-LAST:event_five7ActionPerformed

    private void ten7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten7ActionPerformed
        // TODO add your handling code here:
        if (ten7.isSelected()) {
            five7.setSelected(false);
            fifteen7.setSelected(false);}
          Result7.setText(ten7.getText());
          
    }//GEN-LAST:event_ten7ActionPerformed

    private void five4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five4ActionPerformed
        // TODO add your handling code here:
        if (five4.isSelected()) {
            ten4.setSelected(false);
            fifteen7.setSelected(false);
        }
        Result4.setText(five4.getText());
       
    }//GEN-LAST:event_five4ActionPerformed

    private void ten4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten4ActionPerformed
        // TODO add your handling code here:
        if (ten4.isSelected()) {
            five4.setSelected(false);
            fifteen4.setSelected(false);}
        Result4.setText(ten4.getText());
        
    }//GEN-LAST:event_ten4ActionPerformed

    private void fifteen8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen8ActionPerformed
        // TODO add your handling code here:
         if (fifteen8.isSelected()) {
            five8.setSelected(false);
            ten8.setSelected(false);}
         Result8.setText(fifteen8.getText());
        
    }//GEN-LAST:event_fifteen8ActionPerformed

    private void five8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five8ActionPerformed
        // TODO add your handling code here:
        if (five8.isSelected()) {
            ten8.setSelected(false);
            fifteen8.setSelected(false);
        }
         Result8.setText(five8.getText());
         
    }//GEN-LAST:event_five8ActionPerformed

    private void ten8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten8ActionPerformed
        // TODO add your handling code here:
        if (ten8.isSelected()) {
            five8.setSelected(false);
            fifteen8.setSelected(false);}
         Result8.setText(ten8.getText());
        
    }//GEN-LAST:event_ten8ActionPerformed

    private void fifteen9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen9ActionPerformed
        // TODO add your handling code here:
         if (fifteen9.isSelected()) {
            five9.setSelected(false);
            ten9.setSelected(false);}
          Result9.setText(fifteen9.getText());
         
    }//GEN-LAST:event_fifteen9ActionPerformed

    private void five9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five9ActionPerformed
        // TODO add your handling code here:
        if (five9.isSelected()) {
            ten9.setSelected(false);
            fifteen9.setSelected(false);
        }
        Result9.setText(five9.getText());
        
    }//GEN-LAST:event_five9ActionPerformed

    private void ten9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten9ActionPerformed
        // TODO add your handling code here:
        if (ten9.isSelected()) {
            five9.setSelected(false);
            fifteen9.setSelected(false);}
        Result9.setText(ten9.getText());
       
    }//GEN-LAST:event_ten9ActionPerformed

    private void fifteen10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen10ActionPerformed
        // TODO add your handling code here:
         if (fifteen10.isSelected()) {
            five10.setSelected(false);
            ten10.setSelected(false);}
         Result10.setText(fifteen10.getText());
        
    }//GEN-LAST:event_fifteen10ActionPerformed

    private void five10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five10ActionPerformed
        // TODO add your handling code here:
        if (five10.isSelected()) {
            ten10.setSelected(false);
            fifteen10.setSelected(false);
            Result10.setText(five10.getText());
            
        }
    }//GEN-LAST:event_five10ActionPerformed

    private void ten10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten10ActionPerformed
        // TODO add your handling code here:
        if (ten10.isSelected()) {
            five10.setSelected(false);
            fifteen10.setSelected(false);}
        Result10.setText(ten10.getText());
        
    }//GEN-LAST:event_ten10ActionPerformed

    private void fifteen11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen11ActionPerformed
        // TODO add your handling code here:
         if (fifteen11.isSelected()) {
            five11.setSelected(false);
            ten11.setSelected(false);}
         Result11.setText(fifteen11.getText());
        
    }//GEN-LAST:event_fifteen11ActionPerformed

    private void fifteen12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen12ActionPerformed
        // TODO add your handling code here:
         if (fifteen12.isSelected()) {
            five12.setSelected(false);
            ten12.setSelected(false);}
         Result12.setText(fifteen12.getText());
       
    }//GEN-LAST:event_fifteen12ActionPerformed

    private void five12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five12ActionPerformed
        // TODO add your handling code here:
        if (five12.isSelected()) {
            ten12.setSelected(false);
            fifteen12.setSelected(false);
        }
        Result12.setText(five12.getText());
       
    }//GEN-LAST:event_five12ActionPerformed

    private void ten12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten12ActionPerformed
        // TODO add your handling code here:
        if (ten12.isSelected()) {
            five12.setSelected(false);
            fifteen12.setSelected(false);}
        Result12.setText(ten12.getText());
      
    }//GEN-LAST:event_ten12ActionPerformed

    private void fifteen13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen13ActionPerformed
        // TODO add your handling code here:
         if (fifteen13.isSelected()) {
            five13.setSelected(false);
            ten13.setSelected(false);}
         Result13.setText(fifteen13.getText());
      
    }//GEN-LAST:event_fifteen13ActionPerformed

    private void five13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five13ActionPerformed
        // TODO add your handling code here:
        if (five13.isSelected()) {
            ten13.setSelected(false);
            fifteen13.setSelected(false);
            Result13.setText(five13.getText());
            
        }
    }//GEN-LAST:event_five13ActionPerformed

    private void ten13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten13ActionPerformed
        // TODO add your handling code here:
        if (ten13.isSelected()) {
            five13.setSelected(false);
            fifteen13.setSelected(false);}
        Result13.setText(ten13.getText());
        
    }//GEN-LAST:event_ten13ActionPerformed

    private void fifteen14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen14ActionPerformed
        // TODO add your handling code here:
         if (fifteen14.isSelected()) {
            five14.setSelected(false);
            ten14.setSelected(false);}
         Result14.setText(fifteen14.getText());
         
    }//GEN-LAST:event_fifteen14ActionPerformed

    private void five14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five14ActionPerformed
        // TODO add your handling code here:
        if (five14.isSelected()) {
            ten14.setSelected(false);
            fifteen14.setSelected(false);
        }
         Result14.setText(five14.getText());
        
    }//GEN-LAST:event_five14ActionPerformed

    private void ten14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten14ActionPerformed
        // TODO add your handling code here:
        if (ten14.isSelected()) {
            five14.setSelected(false);
            fifteen14.setSelected(false);}
        Result14.setText(ten14.getText());
       
    }//GEN-LAST:event_ten14ActionPerformed

    private void five11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five11ActionPerformed
        // TODO add your handling code here:
        if (five11.isSelected()) {
            ten11.setSelected(false);
            fifteen11.setSelected(false);
        }
         Result11.setText(five11.getText());
         
    }//GEN-LAST:event_five11ActionPerformed

    private void ten11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten11ActionPerformed
        // TODO add your handling code here:
        if (ten11.isSelected()) {
            five11.setSelected(false);
            fifteen11.setSelected(false);}
         Result11.setText(ten11.getText());
         
    }//GEN-LAST:event_ten11ActionPerformed

    private void ten15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten15ActionPerformed
        // TODO add your handling code here:
        if (ten15.isSelected()) {
            five15.setSelected(false);
            fifteen15.setSelected(false);}
         Result15.setText(ten15.getText());
         
    }//GEN-LAST:event_ten15ActionPerformed

    private void fifteen15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen15ActionPerformed
        // TODO add your handling code here:
         if (fifteen15.isSelected()) {
            five15.setSelected(false);
            ten15.setSelected(false);}
         Result15.setText(fifteen15.getText());
        
    }//GEN-LAST:event_fifteen15ActionPerformed

    private void five15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five15ActionPerformed
        // TODO add your handling code here:
        if (five15.isSelected()) {
            ten15.setSelected(false);
            fifteen15.setSelected(false);
        }
         Result15.setText(five15.getText());
         
    }//GEN-LAST:event_five15ActionPerformed

    private void ten16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten16ActionPerformed
        // TODO add your handling code here:
        if (ten16.isSelected()) {
            five16.setSelected(false);
            fifteen16.setSelected(false);}
         Result16.setText(ten16.getText());
        
    }//GEN-LAST:event_ten16ActionPerformed

    private void ten17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten17ActionPerformed
        // TODO add your handling code here:
        if (ten17.isSelected()) {
            five17.setSelected(false);
            fifteen17.setSelected(false);}
         Result17.setText(ten17.getText());
         
    }//GEN-LAST:event_ten17ActionPerformed

    private void fifteen17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen17ActionPerformed
        // TODO add your handling code here:
         if (fifteen17.isSelected()) {
            five17.setSelected(false);
            ten17.setSelected(false);}
         Result17.setText(fifteen17.getText());
        
    }//GEN-LAST:event_fifteen17ActionPerformed

    private void five17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five17ActionPerformed
        // TODO add your handling code here:
        if (five17.isSelected()) {
            ten17.setSelected(false);
            fifteen17.setSelected(false);
            Result17.setText(five17.getText());
           
        }
    }//GEN-LAST:event_five17ActionPerformed

    private void fifteen16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteen16ActionPerformed
        // TODO add your handling code here:
         if (fifteen16.isSelected()) {
            five16.setSelected(false);
            ten16.setSelected(false);}
          Result16.setText(fifteen16.getText());
         
          
    }//GEN-LAST:event_fifteen16ActionPerformed

    private void five16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five16ActionPerformed
        // TODO add your handling code here:
        if (five16.isSelected()) {
            ten16.setSelected(false);
            fifteen16.setSelected(false);
        }
         Result16.setText(five16.getText());
      
    }//GEN-LAST:event_five16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try{
                 infoEvaluation();
                 this.dispose();
            }catch(Exception x){
               JOptionPane.showMessageDialog(rootPane, "Error");
            }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvaluationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvaluationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvaluationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvaluationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvaluationForm().setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Result0;
    private javax.swing.JLabel Result10;
    private javax.swing.JLabel Result11;
    private javax.swing.JLabel Result12;
    private javax.swing.JLabel Result13;
    private javax.swing.JLabel Result14;
    private javax.swing.JLabel Result15;
    private javax.swing.JLabel Result16;
    private javax.swing.JLabel Result17;
    private javax.swing.JLabel Result2;
    private javax.swing.JLabel Result3;
    private javax.swing.JLabel Result4;
    private javax.swing.JLabel Result5;
    private javax.swing.JLabel Result6;
    private javax.swing.JLabel Result7;
    private javax.swing.JLabel Result8;
    private javax.swing.JLabel Result9;
    private javax.swing.JRadioButton fifteen;
    private javax.swing.JRadioButton fifteen1;
    private javax.swing.JRadioButton fifteen10;
    private javax.swing.JRadioButton fifteen11;
    private javax.swing.JRadioButton fifteen12;
    private javax.swing.JRadioButton fifteen13;
    private javax.swing.JRadioButton fifteen14;
    private javax.swing.JRadioButton fifteen15;
    private javax.swing.JRadioButton fifteen16;
    private javax.swing.JRadioButton fifteen17;
    private javax.swing.JRadioButton fifteen2;
    private javax.swing.JRadioButton fifteen3;
    private javax.swing.JRadioButton fifteen4;
    private javax.swing.JRadioButton fifteen5;
    private javax.swing.JRadioButton fifteen6;
    private javax.swing.JRadioButton fifteen7;
    private javax.swing.JRadioButton fifteen8;
    private javax.swing.JRadioButton fifteen9;
    private javax.swing.JRadioButton five;
    private javax.swing.JRadioButton five1;
    private javax.swing.JRadioButton five10;
    private javax.swing.JRadioButton five11;
    private javax.swing.JRadioButton five12;
    private javax.swing.JRadioButton five13;
    private javax.swing.JRadioButton five14;
    private javax.swing.JRadioButton five15;
    private javax.swing.JRadioButton five16;
    private javax.swing.JRadioButton five17;
    private javax.swing.JRadioButton five2;
    private javax.swing.JRadioButton five3;
    private javax.swing.JRadioButton five4;
    private javax.swing.JRadioButton five5;
    private javax.swing.JRadioButton five6;
    private javax.swing.JRadioButton five7;
    private javax.swing.JRadioButton five8;
    private javax.swing.JRadioButton five9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel result1;
    private javax.swing.JRadioButton ten;
    private javax.swing.JRadioButton ten1;
    private javax.swing.JRadioButton ten10;
    private javax.swing.JRadioButton ten11;
    private javax.swing.JRadioButton ten12;
    private javax.swing.JRadioButton ten13;
    private javax.swing.JRadioButton ten14;
    private javax.swing.JRadioButton ten15;
    private javax.swing.JRadioButton ten16;
    private javax.swing.JRadioButton ten17;
    private javax.swing.JRadioButton ten2;
    private javax.swing.JRadioButton ten3;
    private javax.swing.JRadioButton ten4;
    private javax.swing.JRadioButton ten5;
    private javax.swing.JRadioButton ten6;
    private javax.swing.JRadioButton ten7;
    private javax.swing.JRadioButton ten8;
    private javax.swing.JRadioButton ten9;
    // End of variables declaration//GEN-END:variables

    private void infoMonitoringApp() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    
}
